#!/bin/bash

set -e

if ! [ -d /data/.sketchup-run ] ; then
	echo "Populating the data directory ..."
	mkdir -p /data/.sketchup-run
	( cd /home/user/.local && cp -rp . /data/.sketchup-run/.local/ )
	( cd /home/user/.wine-template && cp -rp . /data/.sketchup-run/wine )
fi
mkdir -p /tmp/wine
( cd /home/user/.tmp-template && cp -rp . /tmp/wine )

# Create SketchUp Plugins directory in the host's home directory, if not already existing
! [ -d /data/SketchUp\ Plugins ] && mkdir /data/SketchUp\ Plugins

export HOME=/data/.sketchup-run
cd /data

# Make space mouse device available to everyone
chmod 0777 /dev/input/event*

# FIXME start spacenavd

exec wine64 $WINEPREFIX/"drive_c/Program Files/SketchUp/SketchUp 2017/SketchUp.exe" "$@"

